apiVersion: apps/v1
kind: Deployment 
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: weezyval/multi-client
          # resources:
          #   limits:
          #     memory: "64Mi"
          #     cpu: "250m"
          ports:
            - containerPort: 3000

       
